version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .docker.env
    networks:
      - postgres
  nestjs:
    build: .
    container_name: nestjs
    ports:
      - "3000:3000"
    networks:
      - postgres
    volumes:
      - .:/src
      - /src/node_modules
    env_file:
      - .env
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
  db-data:
